import type {
  AdapterCapability,
  AdapterManifest,
  LocalDatabaseManifest,
} from './capabilities'
import {
  type ConnectionMode,
  type DatastoreEngine,
  type DatastoreFamily,
} from './connection'
import type { QueryLanguage, ResultRenderer } from './workspace'

export interface DatastoreFeatureBacklogEntry {
  engine: DatastoreEngine
  displayName: string
  family: DatastoreFamily
  maturity: AdapterManifest['maturity']
  defaultLanguage: QueryLanguage
  queryLanguages: QueryLanguage[]
  connectionModes: ConnectionMode[]
  primaryConnectionMechanisms: string[]
  defaultPort?: number
  managementModel: string
  queryModel: string
  presentationModel: string
  securityModel: string
  resultRenderers: ResultRenderer[]
  capabilities: AdapterCapability[]
  baselineFeatures: string[]
  advancedFeatures: string[]
  diagnosticFeatures: string[]
  analyticsSignals: string[]
  roadmapNotes?: string[]
  localDatabase?: LocalDatabaseManifest
}

export const MVP_ADAPTER_ENGINES = [
  'postgresql',
  'cockroachdb',
  'sqlserver',
  'mysql',
  'mariadb',
  'sqlite',
  'mongodb',
  'redis',
] as const satisfies readonly DatastoreEngine[]

const SQL_CORE: AdapterCapability[] = [
  'supports_sql_editor',
  'supports_schema_browser',
  'supports_result_snapshots',
  'supports_import_export',
]

const SQL_ADMIN: AdapterCapability[] = [
  'supports_admin_operations',
  'supports_index_management',
  'supports_user_role_browser',
  'supports_permission_inspection',
  'supports_explain_plan',
  'supports_plan_visualization',
  'supports_query_profile',
  'supports_metrics_collection',
]

const CLOUD_SECURITY: AdapterCapability[] = [
  'supports_cloud_iam',
  'supports_permission_inspection',
]

const tableSchemaPlan = ['table', 'schema', 'json', 'plan', 'profile', 'metrics'] as const
const documentRenderers = ['document', 'json', 'table', 'schema', 'plan', 'profile'] as const
const graphRenderers = ['graph', 'table', 'json', 'plan', 'profile'] as const
const seriesRenderers = ['series', 'chart', 'table', 'metrics', 'json'] as const
const keyValueRenderers = ['keyvalue', 'table', 'json', 'raw', 'metrics'] as const

export const DATASTORE_FEATURE_BACKLOG: DatastoreFeatureBacklogEntry[] = [
  {
    engine: 'postgresql',
    displayName: 'PostgreSQL',
    family: 'sql',
    maturity: 'mvp',
    defaultLanguage: 'sql',
    queryLanguages: ['sql'],
    connectionModes: ['native', 'connection-string'],
    primaryConnectionMechanisms: [
      'Native PostgreSQL protocol through a driver',
      'PostgreSQL connection string with vault-backed secrets',
    ],
    defaultPort: 5432,
    managementModel: 'Relational catalogs with databases, schemas, tables, views, functions, extensions, roles, grants, locks, and sessions.',
    queryModel: 'SQL editor first, with a visual schema/table/filter builder for common SELECT, DDL, index, and row-editing workflows.',
    presentationModel: 'Tabular rows, schema details, JSON EXPLAIN plans, profile output, metrics, and chart-ready statistics.',
    securityModel: 'Database roles, memberships, grants, SSL modes, read-only profiles, and production guardrails determine which actions are enabled.',
    resultRenderers: [...tableSchemaPlan],
    capabilities: [
      ...SQL_CORE,
      ...SQL_ADMIN,
      'supports_transactions',
      'supports_visual_query_builder',
      'supports_query_cancellation',
      'supports_streaming_results',
      'supports_structure_visualization',
      'supports_backup_restore',
      'supports_vector_search',
    ],
    baselineFeatures: [
      'Connect and test profiles',
      'Browse databases, schemas, tables, views, functions, indexes, and extensions',
      'Create/drop tables, add/drop columns, add/drop indexes, and edit rows',
      'SQL editor with saved queries, result snapshots, export, pagination, and streaming',
    ],
    advancedFeatures: [
      'EXPLAIN JSON renderer and guarded EXPLAIN ANALYZE',
      'Locks, sessions, and blocking tree views',
      'pg_stat* panels for table, index, and query health',
      'Vacuum, analyze, and maintenance helpers',
    ],
    diagnosticFeatures: [
      'Plan visualization',
      'Query profile comparison',
      'Query cancellation',
      'Permission-aware disabled DDL/DML actions',
    ],
    analyticsSignals: [
      'Rows returned and execution duration',
      'Shared block reads/hits and temp IO when available',
      'Table/index bloat and vacuum age',
      'Lock waits and active session counts',
    ],
  },
  {
    engine: 'cockroachdb',
    displayName: 'CockroachDB',
    family: 'sql',
    maturity: 'mvp',
    defaultLanguage: 'sql',
    queryLanguages: ['sql'],
    connectionModes: ['native', 'connection-string', 'cloud-iam'],
    primaryConnectionMechanisms: [
      'PostgreSQL-compatible wire protocol through a driver',
      'CockroachDB connection string with TLS and vault-backed secrets',
      'Managed CockroachDB Cloud identity or certificate-based profiles where available',
    ],
    defaultPort: 26257,
    managementModel: 'Distributed SQL catalogs with databases, schemas, tables, indexes, constraints, ranges, regions, jobs, sessions, contention, roles, and grants.',
    queryModel: 'SQL editor first, with guarded DDL/table/index builders and Cockroach-specific SHOW/crdb_internal diagnostic templates.',
    presentationModel: 'Tabular rows, schema details, distributed SQL plans, EXPLAIN ANALYZE profiles, jobs, contention, latency metrics, and chart-ready cluster signals.',
    securityModel: 'SQL users, roles, grants/default privileges, TLS/certificates, cloud IAM signals, read-only profiles, and production guardrails for DDL/admin operations.',
    resultRenderers: [...tableSchemaPlan, 'series'],
    capabilities: [
      ...SQL_CORE,
      ...SQL_ADMIN,
      ...CLOUD_SECURITY,
      'supports_transactions',
      'supports_visual_query_builder',
      'supports_query_cancellation',
      'supports_streaming_results',
      'supports_structure_visualization',
      'supports_backup_restore',
      'supports_import_export',
    ],
    baselineFeatures: [
      'Connect through pgwire, connection strings, or cloud identity profiles',
      'Browse databases, schemas, tables, columns, indexes, constraints, ranges, regions, jobs, sessions, roles, and grants',
      'SQL editor, row editing, guarded table/index/column operations, and saved query workflows',
      'Cockroach-specific SHOW helpers for roles, grants, jobs, cluster settings, and node status',
    ],
    advancedFeatures: [
      'Distributed EXPLAIN plan rendering and guarded EXPLAIN ANALYZE (DISTSQL)',
      'Contention, session, job, range, and node status panels',
      'Role, grant, and default privilege inspection',
      'Backup/restore and import/export operation plans with explicit confirmation',
    ],
    diagnosticFeatures: [
      'Plan visualization',
      'Query profile and contention analysis',
      'Job progress, latency, and node health dashboards',
      'Permission-aware disabled DDL, backup, restore, and admin actions',
    ],
    analyticsSignals: [
      'Execution duration, rows read, and rows returned',
      'Contention events and lock wait signals',
      'Job status/progress and range distribution',
      'Cluster/node liveness, latency, and SQL session counts',
    ],
    roadmapNotes: [
      'Use information_schema, pg_catalog, and supported SHOW statements by default; use production-supported crdb_internal objects only when permitted.',
      'Treat EXPLAIN ANALYZE and backup/restore as guarded operations because they execute workload or mutate cluster state.',
    ],
  },
  {
    engine: 'sqlserver',
    displayName: 'SQL Server / Azure SQL',
    family: 'sql',
    maturity: 'mvp',
    defaultLanguage: 'sql',
    queryLanguages: ['sql'],
    connectionModes: ['native', 'connection-string', 'cloud-iam'],
    primaryConnectionMechanisms: [
      'TDS driver connection',
      'ADO-style connection string',
      'Azure SQL with Entra identity as a planned cloud IAM path',
    ],
    defaultPort: 1433,
    managementModel: 'Relational catalogs with databases, schemas, tables, views, procedures, functions, indexes, logins, users, roles, DMVs, and Query Store.',
    queryModel: 'T-SQL editor plus visual table/schema builders for common SELECT and DDL tasks.',
    presentationModel: 'Tables, schema views, XML/JSON showplans, Query Store history, DMV metrics, and dashboard charts.',
    securityModel: 'Server logins, database users, roles, object grants, Entra identity, encrypted connections, and read-only profile guardrails.',
    resultRenderers: [...tableSchemaPlan],
    capabilities: [
      ...SQL_CORE,
      ...SQL_ADMIN,
      ...CLOUD_SECURITY,
      'supports_transactions',
      'supports_visual_query_builder',
      'supports_query_cancellation',
      'supports_structure_visualization',
      'supports_cost_estimation',
    ],
    baselineFeatures: [
      'Connect and browse database objects',
      'Schema/table/view/procedure/index browser',
      'Create/drop tables, add/drop columns and indexes',
      'T-SQL editor with saved queries, snapshots, and export',
    ],
    advancedFeatures: [
      'Estimated and actual execution plan rendering',
      'Query Store history and regressions',
      'DMV dashboards for waits, sessions, locks, and IO',
      'Role and permission inspection',
    ],
    diagnosticFeatures: [
      'Showplan visualization',
      'Query Store drilldown',
      'Live session cancellation',
      'Permission-aware DDL enablement',
    ],
    analyticsSignals: [
      'CPU, duration, reads, writes, and row counts',
      'Wait categories and blocking sessions',
      'Query Store runtime stats',
      'Index usage and missing-index hints',
    ],
  },
  {
    engine: 'mysql',
    displayName: 'MySQL',
    family: 'sql',
    maturity: 'mvp',
    defaultLanguage: 'sql',
    queryLanguages: ['sql'],
    connectionModes: ['native', 'connection-string'],
    primaryConnectionMechanisms: [
      'Native MySQL protocol through a driver',
      'MySQL connection string with vault-backed password',
    ],
    defaultPort: 3306,
    managementModel: 'Relational schemas with tables, views, routines, indexes, foreign keys, accounts, host privileges, INFORMATION_SCHEMA, and performance_schema.',
    queryModel: 'SQL editor plus visual builders for SELECT filters, table structure edits, indexes, and row edits.',
    presentationModel: 'Tables, DESCRIBE/SHOW metadata, JSON/text plans, performance schema metrics, and charts.',
    securityModel: 'User@host accounts, grants, SSL mode, read-only profiles, and production-safe destructive-action blocks.',
    resultRenderers: [...tableSchemaPlan],
    capabilities: [
      ...SQL_CORE,
      ...SQL_ADMIN,
      'supports_transactions',
      'supports_visual_query_builder',
      'supports_streaming_results',
      'supports_structure_visualization',
      'supports_backup_restore',
    ],
    baselineFeatures: [
      'Table, column, index, foreign key, view, and routine browser',
      'Create/drop tables, add/drop columns, add/drop indexes, and edit rows',
      'DESCRIBE and SHOW helpers',
      'SQL editor with snapshots, pagination, and export',
    ],
    advancedFeatures: [
      'EXPLAIN and ANALYZE rendering',
      'Slow query and performance_schema panels',
      'User and privilege browser',
      'Engine/status panels',
    ],
    diagnosticFeatures: [
      'Plan table visualization',
      'Slow query review',
      'Performance schema summaries',
      'Privilege-aware disabled writes',
    ],
    analyticsSignals: [
      'Rows examined and rows returned',
      'Handler counters and temp table use',
      'Slow query counts',
      'Buffer pool and connection metrics',
    ],
  },
  {
    engine: 'mariadb',
    displayName: 'MariaDB',
    family: 'sql',
    maturity: 'mvp',
    defaultLanguage: 'sql',
    queryLanguages: ['sql'],
    connectionModes: ['native', 'connection-string'],
    primaryConnectionMechanisms: [
      'Native MySQL-compatible protocol',
      'MariaDB/MySQL connection string with vault-backed password',
    ],
    defaultPort: 3306,
    managementModel: 'MySQL-like schemas plus MariaDB roles, storage engines, optimizer traces, status variables, and ANALYZE behavior.',
    queryModel: 'SQL editor and MySQL-compatible visual builders, with MariaDB-specific explain/profile rendering where available.',
    presentationModel: 'Tables, schema metadata, text/JSON plans, engine/status metrics, and charts.',
    securityModel: 'User accounts, roles, grants, SSL, read-only profiles, and production-safe guardrails.',
    resultRenderers: [...tableSchemaPlan],
    capabilities: [
      ...SQL_CORE,
      ...SQL_ADMIN,
      'supports_transactions',
      'supports_visual_query_builder',
      'supports_streaming_results',
      'supports_structure_visualization',
      'supports_backup_restore',
    ],
    baselineFeatures: [
      'Table, column, index, foreign key, view, and routine CRUD',
      'SQL editor with DESCRIBE/SHOW shortcuts',
      'Role-aware metadata browser',
      'Saved queries, snapshots, pagination, and export',
    ],
    advancedFeatures: [
      'MariaDB-specific EXPLAIN and ANALYZE output',
      'Role management and grant inspection',
      'Storage engine and status dashboards',
      'Slow query analysis',
    ],
    diagnosticFeatures: [
      'Plan and optimizer output renderer',
      'Status variable charts',
      'Privilege-aware admin controls',
      'Slow query panels',
    ],
    analyticsSignals: [
      'Rows examined, rows sent, and temp tables',
      'Engine status counters',
      'Connections and thread cache metrics',
      'Index usage indicators',
    ],
  },
  {
    engine: 'sqlite',
    displayName: 'SQLite',
    family: 'sql',
    maturity: 'mvp',
    defaultLanguage: 'sql',
    queryLanguages: ['sql'],
    connectionModes: ['local-file', 'connection-string'],
    primaryConnectionMechanisms: [
      'Local database file',
      'SQLite URI connection string',
    ],
    managementModel: 'Embedded file database with tables, views, triggers, indexes, PRAGMA metadata, and file-level access controls.',
    queryModel: 'SQL editor, file open/create workflows, and visual builders for tables, indexes, views, triggers, and row edits.',
    presentationModel: 'Tables, schema metadata, raw EXPLAIN QUERY PLAN rows, PRAGMA outputs, and export files.',
    securityModel: 'File-system permissions, optional application-level read-only mode, secret-free local profiles, and destructive-action guardrails.',
    resultRenderers: ['table', 'schema', 'json', 'plan', 'raw'],
    capabilities: [
      ...SQL_CORE,
      'supports_local_database_creation',
      'supports_admin_operations',
      'supports_index_management',
      'supports_explain_plan',
      'supports_plan_visualization',
      'supports_query_profile',
      'supports_import_export',
      'supports_backup_restore',
      'supports_structure_visualization',
    ],
    localDatabase: {
      defaultExtension: 'sqlite',
      extensions: ['sqlite', 'sqlite3', 'db'],
      canCreateEmpty: true,
      canCreateStarter: true,
    },
    baselineFeatures: [
      'Open and create local database files',
      'Create/drop tables, indexes, views, and triggers',
      'PRAGMA schema browser',
      'SQL editor with snapshots and export',
    ],
    advancedFeatures: [
      'EXPLAIN QUERY PLAN renderer',
      'Integrity check workflow',
      'Vacuum/analyze helpers',
      'Local backup/export',
    ],
    diagnosticFeatures: [
      'Query plan rows',
      'Integrity check output',
      'Database page/cache PRAGMAs',
      'Read-only file warnings',
    ],
    analyticsSignals: [
      'Page count and freelist count',
      'Execution duration',
      'Row counts',
      'Integrity check status',
    ],
  },
  {
    engine: 'oracle',
    displayName: 'Oracle',
    family: 'sql',
    maturity: 'beta',
    defaultLanguage: 'sql',
    queryLanguages: ['sql'],
    connectionModes: ['native', 'connection-string'],
    primaryConnectionMechanisms: [
      'Oracle native driver/TNS connection',
      'Oracle connection string with wallet/secret references',
    ],
    defaultPort: 1521,
    managementModel: 'Enterprise relational catalogs with schemas, tables, indexes, sequences, packages, dictionary views, users, roles, profiles, and grants.',
    queryModel: 'SQL/PLSQL editor with visual object browser and guarded DDL helpers.',
    presentationModel: 'Tables, dictionary metadata, DBMS_XPLAN-style plans, session/wait metrics, and charts.',
    securityModel: 'Users, roles, object grants, system privileges, wallet secrets, SSL, and profile-aware read-only restrictions.',
    resultRenderers: [...tableSchemaPlan],
    capabilities: [
      ...SQL_CORE,
      ...SQL_ADMIN,
      'supports_transactions',
      'supports_visual_query_builder',
      'supports_query_cancellation',
      'supports_structure_visualization',
      'supports_backup_restore',
    ],
    baselineFeatures: [
      'Schema/table/index/sequence/package browser',
      'DDL editor and object creation helpers',
      'SQL/PLSQL editor with saved queries and export',
      'Object grants viewer',
    ],
    advancedFeatures: [
      'EXPLAIN PLAN and DBMS_XPLAN renderer',
      'Session and wait metrics',
      'Role and privilege inspection',
      'Package/procedure workflow support',
    ],
    diagnosticFeatures: [
      'Plan visualization',
      'Session wait analysis',
      'Long-running query cancellation',
      'Permission-aware admin controls',
    ],
    analyticsSignals: [
      'Elapsed time, CPU, logical reads, and physical reads',
      'Wait events',
      'Segment and index stats',
      'Session counts',
    ],
  },
  {
    engine: 'timescaledb',
    displayName: 'TimescaleDB',
    family: 'timeseries',
    maturity: 'beta',
    defaultLanguage: 'sql',
    queryLanguages: ['sql'],
    connectionModes: ['native', 'connection-string'],
    primaryConnectionMechanisms: [
      'PostgreSQL protocol through a driver',
      'PostgreSQL-compatible connection string',
    ],
    defaultPort: 5432,
    managementModel: 'PostgreSQL plus hypertables, chunks, compression, continuous aggregates, retention policies, and time-series jobs.',
    queryModel: 'SQL editor and chart-first visual query builder for time buckets, filters, aggregations, and retention/compression workflows.',
    presentationModel: 'Tables, chart-ready series, hypertable/chunk schema, plans, metrics, and dashboards.',
    securityModel: 'PostgreSQL roles/grants plus extension object permissions and read-only/production guardrails.',
    resultRenderers: ['series', 'chart', 'table', 'schema', 'plan', 'metrics'],
    capabilities: [
      ...SQL_CORE,
      ...SQL_ADMIN,
      'supports_time_series_charting',
      'supports_visual_query_builder',
      'supports_query_cancellation',
      'supports_streaming_results',
      'supports_structure_visualization',
    ],
    baselineFeatures: [
      'All PostgreSQL baseline features',
      'Hypertable and chunk explorer',
      'Time-bucket query templates',
      'Chart-first result rendering',
    ],
    advancedFeatures: [
      'Continuous aggregate management',
      'Compression and retention workflows',
      'Chunk stats and policy status',
      'Time-series dashboards',
    ],
    diagnosticFeatures: [
      'Chunk health panels',
      'Continuous aggregate freshness',
      'Plan/profile output',
      'Retention/compression policy warnings',
    ],
    analyticsSignals: [
      'Chunk size and row counts',
      'Compression ratio',
      'Continuous aggregate lag',
      'Query duration by time window',
    ],
  },
  {
    engine: 'mongodb',
    displayName: 'MongoDB',
    family: 'document',
    maturity: 'mvp',
    defaultLanguage: 'mongodb',
    queryLanguages: ['mongodb', 'json'],
    connectionModes: ['native', 'connection-string'],
    primaryConnectionMechanisms: [
      'MongoDB wire protocol driver',
      'MongoDB URI connection string with SCRAM/X.509/OIDC options',
    ],
    defaultPort: 27017,
    managementModel: 'BSON document databases with collections, indexes, validators, views, replica/shard topology, users, roles, and privileges.',
    queryModel: 'Visual find/filter builder, aggregation pipeline builder, and raw MongoDB JSON command editor.',
    presentationModel: 'Documents, JSON, inferred tables, collection schemas, explain/profile output, and metrics.',
    securityModel: 'Database users, roles, collection privileges, auth mechanisms, TLS, read-only profiles, and destructive-command guardrails.',
    resultRenderers: [...documentRenderers],
    capabilities: [
      'supports_document_view',
      'supports_visual_query_builder',
      'supports_result_snapshots',
      'supports_streaming_results',
      'supports_schema_browser',
      'supports_admin_operations',
      'supports_index_management',
      'supports_user_role_browser',
      'supports_permission_inspection',
      'supports_explain_plan',
      'supports_plan_visualization',
      'supports_query_profile',
      'supports_metrics_collection',
      'supports_import_export',
      'supports_backup_restore',
      'supports_vector_search',
      'supports_structure_visualization',
    ],
    baselineFeatures: [
      'Database and collection browser',
      'Add/drop collection',
      'Document CRUD and table-style document view',
      'Index CRUD, visual find/filter builder, and aggregation pipeline builder',
    ],
    advancedFeatures: [
      'Explain renderer',
      '$indexStats and query stats panels',
      'Schema inference and validation editor',
      'Shard and replica metrics',
    ],
    diagnosticFeatures: [
      'Winning/rejected plan rendering',
      'Index usage stats',
      'Collection and server metrics',
      'Permission-aware command blocking',
    ],
    analyticsSignals: [
      'Documents examined and returned',
      'Index hit ratio',
      'Collection size and storage size',
      'Replica lag and shard distribution',
    ],
  },
  {
    engine: 'dynamodb',
    displayName: 'DynamoDB',
    family: 'widecolumn',
    maturity: 'beta',
    defaultLanguage: 'json',
    queryLanguages: ['json'],
    connectionModes: ['cloud-iam', 'cloud-sdk'],
    primaryConnectionMechanisms: [
      'AWS SDK with IAM credentials or role assumption',
      'Endpoint override for local/test DynamoDB',
    ],
    defaultPort: 8000,
    managementModel: 'Serverless tables with partition/sort keys, items, GSIs, LSIs, TTL, streams, capacity mode, and CloudWatch metrics.',
    queryModel: 'Partition-key-first Query builder, Scan builder with warnings, PartiQL as a future editor mode, and raw AWS API JSON.',
    presentationModel: 'Items as key-value/document rows, table/index metadata, consumed capacity, CloudWatch metrics, and cost charts.',
    securityModel: 'AWS IAM policies, resource ARNs, temporary credentials, SigV4, read-only profiles, and production scan/write guardrails.',
    resultRenderers: ['keyvalue', 'document', 'table', 'metrics', 'costEstimate'],
    capabilities: [
      'supports_document_view',
      'supports_key_browser',
      'supports_schema_browser',
      'supports_visual_query_builder',
      'supports_result_snapshots',
      'supports_admin_operations',
      'supports_index_management',
      'supports_permission_inspection',
      'supports_cloud_iam',
      'supports_metrics_collection',
      'supports_cost_estimation',
      'supports_import_export',
      'supports_streaming_results',
    ],
    baselineFeatures: [
      'Table and item browser',
      'Key-condition Query builder',
      'GSI/LSI viewer and add/drop GSI workflow',
      'TTL and streams viewer',
    ],
    advancedFeatures: [
      'Consumed capacity display',
      'CloudWatch throttle and latency dashboards',
      'Cost estimate panels',
      'Single-table modeling hints',
    ],
    diagnosticFeatures: [
      'Scan warning guardrails',
      'Hot partition indicators',
      'Consumed capacity charts',
      'IAM permission explanations',
    ],
    analyticsSignals: [
      'Read/write capacity units',
      'Throttled requests',
      'Returned item count and scanned count',
      'Estimated request cost',
    ],
  },
  {
    engine: 'cassandra',
    displayName: 'Cassandra',
    family: 'widecolumn',
    maturity: 'beta',
    defaultLanguage: 'cql',
    queryLanguages: ['cql'],
    connectionModes: ['native', 'connection-string'],
    primaryConnectionMechanisms: [
      'Cassandra native protocol driver',
      'Contact-point connection profile with TLS and credentials',
    ],
    defaultPort: 9042,
    managementModel: 'Distributed wide-column keyspaces with tables, UDTs, indexes, materialized views, roles, permissions, tracing, compaction, and repair state.',
    queryModel: 'CQL editor plus partition-key-aware visual builder that keeps users inside Cassandra query rules.',
    presentationModel: 'Tabular results, keyspace/table metadata, tracing spans, nodetool/JMX metrics, and charts.',
    securityModel: 'Roles, permissions, TLS, auth providers, and guardrails for token-range scans and admin operations.',
    resultRenderers: ['table', 'schema', 'metrics', 'plan', 'profile'],
    capabilities: [
      'supports_schema_browser',
      'supports_result_snapshots',
      'supports_visual_query_builder',
      'supports_admin_operations',
      'supports_index_management',
      'supports_user_role_browser',
      'supports_permission_inspection',
      'supports_query_profile',
      'supports_metrics_collection',
      'supports_streaming_results',
      'supports_structure_visualization',
    ],
    baselineFeatures: [
      'Keyspace, table, type, index, and materialized-view browser',
      'CQL editor',
      'Partition-key visual query builder',
      'Role and permission browser',
    ],
    advancedFeatures: [
      'SAI/index guidance',
      'Query tracing',
      'Nodetool/JMX readouts',
      'Repair and compaction status',
    ],
    diagnosticFeatures: [
      'Tracing timeline',
      'Compaction/repair panels',
      'Partition scan warnings',
      'Permission-aware admin actions',
    ],
    analyticsSignals: [
      'Read/write latency',
      'Tombstone warnings',
      'SSTable and compaction metrics',
      'Coordinator and replica timing',
    ],
  },
  {
    engine: 'cosmosdb',
    displayName: 'Cosmos DB',
    family: 'document',
    maturity: 'beta',
    defaultLanguage: 'sql',
    queryLanguages: ['sql', 'mongodb', 'cql', 'gremlin'],
    connectionModes: ['cloud-iam', 'cloud-sdk', 'connection-string'],
    primaryConnectionMechanisms: [
      'Azure SDK with Entra identity or account keys',
      'API-specific connection strings for SQL, MongoDB, Cassandra, Gremlin, or Table APIs',
    ],
    defaultPort: 443,
    managementModel: 'Managed multi-model accounts with databases, containers, partition keys, indexing policies, throughput, regions, and per-API objects.',
    queryModel: 'SQL API query builder first, then API-specific Mongo/Cassandra/Gremlin/Table adapters.',
    presentationModel: 'JSON documents, tabular projections, RU charge metrics, query metrics, index metrics, latency charts, and partition views.',
    securityModel: 'Azure RBAC, keys, resource tokens, private endpoints, Entra identity, and permission-aware account/container actions.',
    resultRenderers: ['document', 'table', 'json', 'metrics', 'series', 'costEstimate'],
    capabilities: [
      'supports_document_view',
      'supports_schema_browser',
      'supports_visual_query_builder',
      'supports_result_snapshots',
      'supports_admin_operations',
      'supports_index_management',
      'supports_permission_inspection',
      'supports_cloud_iam',
      'supports_metrics_collection',
      'supports_cost_estimation',
      'supports_import_export',
      'supports_query_profile',
    ],
    baselineFeatures: [
      'Account, database, and container browser',
      'SQL query builder',
      'Partition key and indexing policy viewer',
      'Document/item browser with export',
    ],
    advancedFeatures: [
      'RU charge and query metrics',
      'Index metrics and latency charts',
      'Per-API adapters',
      'Throughput and region dashboards',
    ],
    diagnosticFeatures: [
      'RU and latency panels',
      'Cross-partition query warnings',
      'Index utilization reporting',
      'Azure RBAC explanations',
    ],
    analyticsSignals: [
      'RU charge',
      'Request latency',
      'Document count and storage',
      'Throttles and region failover events',
    ],
  },
  {
    engine: 'litedb',
    displayName: 'LiteDB',
    family: 'document',
    maturity: 'beta',
    defaultLanguage: 'json',
    queryLanguages: ['json'],
    connectionModes: ['local-file', 'connection-string'],
    primaryConnectionMechanisms: [
      'Local LiteDB file',
      '.NET LiteDB connection string with optional password',
    ],
    managementModel: 'Embedded .NET document database with collections, BSON documents, indexes, file passwords, and local storage management.',
    queryModel: 'Collection query editor, visual filter builder, and raw JSON query document.',
    presentationModel: 'Documents, tabular projections, collection/index metadata, raw JSON, and import/export files.',
    securityModel: 'Local file permissions, optional database password/encryption, and read-only profile guardrails.',
    resultRenderers: ['document', 'table', 'json', 'schema', 'raw'],
    capabilities: [
      'supports_document_view',
      'supports_schema_browser',
      'supports_visual_query_builder',
      'supports_result_snapshots',
      'supports_local_database_creation',
      'supports_index_management',
      'supports_import_export',
      'supports_backup_restore',
    ],
    baselineFeatures: [
      'Open/create local LiteDB file',
      'Collection/document/index CRUD',
      'Query editor',
      'Import/export',
    ],
    advancedFeatures: [
      'Password/encryption handling',
      'Schema sampling',
      'File backup workflow',
      'Collection compaction status',
    ],
    diagnosticFeatures: [
      'File accessibility checks',
      'Index and collection size readouts',
      'Read-only file warnings',
      'Schema drift samples',
    ],
    analyticsSignals: [
      'Collection document counts',
      'Index counts',
      'File size',
      'Query duration',
    ],
  },
  {
    engine: 'redis',
    displayName: 'Redis',
    family: 'keyvalue',
    maturity: 'mvp',
    defaultLanguage: 'redis',
    queryLanguages: ['redis', 'text'],
    connectionModes: ['native', 'connection-string'],
    primaryConnectionMechanisms: [
      'RESP protocol driver',
      'Redis URI with TLS, username, and secret references',
    ],
    defaultPort: 6379,
    managementModel: 'In-memory data structures with keys, types, TTLs, streams, modules, ACLs, INFO, SLOWLOG, memory, latency, and cluster topology.',
    queryModel: 'Command console plus key browser, SCAN builder, and type-aware editors for strings, hashes, lists, sets, sorted sets, streams, JSON, and search modules.',
    presentationModel: 'Key-value/type views, raw command output, INFO/SLOWLOG metrics, stream entries, and charts.',
    securityModel: 'ACL users/categories, TLS, passwords, read-only profiles, and guarded write/delete/flush commands.',
    resultRenderers: [...keyValueRenderers],
    capabilities: [
      'supports_key_browser',
      'supports_ttl_management',
      'supports_result_snapshots',
      'supports_streaming_results',
      'supports_admin_operations',
      'supports_user_role_browser',
      'supports_permission_inspection',
      'supports_metrics_collection',
      'supports_import_export',
      'supports_vector_search',
      'supports_structure_visualization',
    ],
    baselineFeatures: [
      'Key browser with SCAN',
      'GET/HGETALL and type-aware editors',
      'Set/remove TTL',
      'Delete and rename keys with guardrails',
    ],
    advancedFeatures: [
      'Memory, latency, commandstats, and hit-rate charts',
      'ACL viewer',
      'Streams support',
      'JSON/Search module support',
    ],
    diagnosticFeatures: [
      'INFO dashboards',
      'SLOWLOG panel',
      'Memory usage inspection',
      'ACL-aware disabled commands',
    ],
    analyticsSignals: [
      'Memory usage and evictions',
      'Ops/sec and command stats',
      'Keyspace hits/misses',
      'Latency percentiles',
    ],
  },
  {
    engine: 'valkey',
    displayName: 'Valkey',
    family: 'keyvalue',
    maturity: 'beta',
    defaultLanguage: 'redis',
    queryLanguages: ['redis', 'text'],
    connectionModes: ['native', 'connection-string'],
    primaryConnectionMechanisms: [
      'RESP protocol driver',
      'Valkey/Redis-compatible URI',
    ],
    defaultPort: 6379,
    managementModel: 'Redis-compatible in-memory data structures with keys, TTL, ACLs, INFO, SLOWLOG, cluster topology, and module-aware extension points.',
    queryModel: 'Redis-compatible command console, key browser, SCAN builder, and type-aware editors.',
    presentationModel: 'Key-value/type output, raw command output, INFO/SLOWLOG metrics, and charts.',
    securityModel: 'ACL users/categories, TLS, secret references, read-only profiles, and guarded write/delete/flush commands.',
    resultRenderers: [...keyValueRenderers],
    capabilities: [
      'supports_key_browser',
      'supports_ttl_management',
      'supports_result_snapshots',
      'supports_streaming_results',
      'supports_admin_operations',
      'supports_user_role_browser',
      'supports_permission_inspection',
      'supports_metrics_collection',
      'supports_import_export',
      'supports_structure_visualization',
    ],
    baselineFeatures: [
      'Redis-compatible key browser',
      'SCAN, GET, HGETALL, and type-aware editors',
      'TTL management',
      'Delete and rename with guardrails',
    ],
    advancedFeatures: [
      'Memory, latency, commandstats, and hit-rate charts',
      'ACL viewer',
      'Streams support',
      'Cluster topology',
    ],
    diagnosticFeatures: [
      'INFO dashboards',
      'SLOWLOG panel',
      'Memory usage inspection',
      'ACL-aware disabled commands',
    ],
    analyticsSignals: [
      'Memory usage and evictions',
      'Ops/sec and command stats',
      'Keyspace hits/misses',
      'Latency percentiles',
    ],
  },
  {
    engine: 'memcached',
    displayName: 'Memcached',
    family: 'keyvalue',
    maturity: 'beta',
    defaultLanguage: 'text',
    queryLanguages: ['text'],
    connectionModes: ['native', 'connection-string'],
    primaryConnectionMechanisms: [
      'Memcached text or binary protocol',
      'Server list with optional SASL credentials',
    ],
    defaultPort: 11211,
    managementModel: 'Ephemeral cache nodes with simple keys, values, TTL, counters, slabs, item stats, and optional SASL.',
    queryModel: 'Command/action forms for get, set, delete, incr, decr, stats, and prefix sampling.',
    presentationModel: 'Key-value output, raw stats, slab dashboards, hit-rate charts, and eviction panels.',
    securityModel: 'Network ACLs, SASL where available, read-only profiles, and guarded mutation commands.',
    resultRenderers: [...keyValueRenderers],
    capabilities: [
      'supports_key_browser',
      'supports_ttl_management',
      'supports_result_snapshots',
      'supports_metrics_collection',
      'supports_import_export',
    ],
    baselineFeatures: [
      'Server stats',
      'Get/set/delete/incr/decr',
      'Prefix sampling',
      'TTL-aware value editor',
    ],
    advancedFeatures: [
      'Slab dashboards',
      'Hit-rate dashboards',
      'Eviction charts',
      'Item-size analysis',
    ],
    diagnosticFeatures: [
      'Stats panels',
      'Slab and eviction readouts',
      'Network ACL warnings',
      'Mutation guardrails',
    ],
    analyticsSignals: [
      'Get hits/misses',
      'Evictions and reclaimed items',
      'Bytes used',
      'Connection counts',
    ],
  },
  {
    engine: 'neo4j',
    displayName: 'Neo4j',
    family: 'graph',
    maturity: 'beta',
    defaultLanguage: 'cypher',
    queryLanguages: ['cypher'],
    connectionModes: ['native', 'connection-string'],
    primaryConnectionMechanisms: [
      'Bolt driver connection',
      'Neo4j URI with TLS and auth',
    ],
    defaultPort: 7687,
    managementModel: 'Property graph databases with nodes, relationships, labels, relationship types, indexes, constraints, users, roles, privileges, and databases.',
    queryModel: 'Cypher editor plus visual graph pattern builder and schema-aware templates.',
    presentationModel: 'Graph visualization, paths, tables, JSON, EXPLAIN/PROFILE plans, and metrics.',
    securityModel: 'Neo4j users, roles, privileges, database access, TLS, read-only profiles, and guarded writes.',
    resultRenderers: [...graphRenderers],
    capabilities: [
      'supports_graph_view',
      'supports_schema_browser',
      'supports_visual_query_builder',
      'supports_result_snapshots',
      'supports_admin_operations',
      'supports_index_management',
      'supports_user_role_browser',
      'supports_permission_inspection',
      'supports_explain_plan',
      'supports_plan_visualization',
      'supports_query_profile',
      'supports_metrics_collection',
      'supports_structure_visualization',
      'supports_vector_search',
    ],
    baselineFeatures: [
      'Database, node-label, relationship, index, and constraint browser',
      'Cypher editor',
      'Graph renderer',
      'Saved graph queries and exports',
    ],
    advancedFeatures: [
      'EXPLAIN/PROFILE operator plan',
      'Role/security browser',
      'GDS workflow hooks',
      'Vector index support',
    ],
    diagnosticFeatures: [
      'Operator plan visualization',
      'DB hits and row counts',
      'Privilege-aware disabled writes',
      'Graph rendering limits',
    ],
    analyticsSignals: [
      'DB hits and allocated memory',
      'Rows per plan operator',
      'Node and relationship counts',
      'Query duration',
    ],
  },
  {
    engine: 'neptune',
    displayName: 'Amazon Neptune',
    family: 'graph',
    maturity: 'beta',
    defaultLanguage: 'gremlin',
    queryLanguages: ['gremlin', 'sparql', 'cypher'],
    connectionModes: ['cloud-iam', 'cloud-sdk', 'connection-string'],
    primaryConnectionMechanisms: [
      'Gremlin/openCypher/SPARQL endpoints',
      'AWS SigV4/IAM through SDK or signed HTTP',
    ],
    defaultPort: 8182,
    managementModel: 'Managed graph clusters with Gremlin, openCypher, and SPARQL endpoints, cluster status, queries, bulk loader jobs, IAM, and CloudWatch metrics.',
    queryModel: 'Language-specific editors with graph/RDF result rendering and status/cancel controls.',
    presentationModel: 'Graph paths, RDF triples/tables, JSON, explain/profile output, loader status, and CloudWatch charts.',
    securityModel: 'AWS IAM/SigV4, VPC/network security, TLS, endpoint auth, and permission-aware cloud actions.',
    resultRenderers: [...graphRenderers, 'metrics'],
    capabilities: [
      'supports_graph_view',
      'supports_result_snapshots',
      'supports_explain_plan',
      'supports_plan_visualization',
      'supports_query_profile',
      'supports_query_cancellation',
      'supports_cloud_iam',
      'supports_metrics_collection',
      'supports_import_export',
      'supports_structure_visualization',
    ],
    baselineFeatures: [
      'Gremlin, openCypher, and SPARQL editors',
      'Graph and RDF renderers',
      'Query status and cancel controls',
      'Cluster status browser',
    ],
    advancedFeatures: [
      'Gremlin/openCypher/SPARQL explain/profile',
      'CloudWatch metrics',
      'Bulk loader workflows',
      'IAM policy explanations',
    ],
    diagnosticFeatures: [
      'Explain/profile renderer',
      'Running query cancellation',
      'Loader job status',
      'CloudWatch dashboards',
    ],
    analyticsSignals: [
      'Query duration',
      'Engine CPU and memory',
      'Gremlin requests and errors',
      'Loader throughput',
    ],
  },
  {
    engine: 'arango',
    displayName: 'ArangoDB',
    family: 'graph',
    maturity: 'beta',
    defaultLanguage: 'aql',
    queryLanguages: ['aql'],
    connectionModes: ['native', 'connection-string'],
    primaryConnectionMechanisms: [
      'ArangoDB HTTP API',
      'Connection URL with JWT/basic auth',
    ],
    defaultPort: 8529,
    managementModel: 'Multi-model databases with document collections, edge collections, named graphs, indexes, users, permissions, and services.',
    queryModel: 'AQL editor, collection/document/edge browser, and graph pattern helpers.',
    presentationModel: 'Documents, graph views, tables, AQL explain/profile plans, and metrics.',
    securityModel: 'Users, database and collection permissions, JWT/basic auth, TLS, and read-only profile guardrails.',
    resultRenderers: ['document', 'graph', 'table', 'json', 'plan', 'profile'],
    capabilities: [
      'supports_document_view',
      'supports_graph_view',
      'supports_schema_browser',
      'supports_visual_query_builder',
      'supports_result_snapshots',
      'supports_admin_operations',
      'supports_index_management',
      'supports_user_role_browser',
      'supports_permission_inspection',
      'supports_explain_plan',
      'supports_plan_visualization',
      'supports_query_profile',
      'supports_metrics_collection',
      'supports_structure_visualization',
    ],
    baselineFeatures: [
      'Collection, document, edge, and graph browser',
      'AQL editor',
      'Index CRUD',
      'Graph and document result renderers',
    ],
    advancedFeatures: [
      'AQL explain/profile plan charts',
      'User/database/collection permission viewer',
      'Foxx/service admin later',
      'Cluster health panels',
    ],
    diagnosticFeatures: [
      'AQL plan visualization',
      'Profile stage timing',
      'Permission-aware actions',
      'Cluster metrics',
    ],
    analyticsSignals: [
      'Execution time and scanned rows',
      'Plan node estimates',
      'Collection counts and sizes',
      'Cluster request metrics',
    ],
  },
  {
    engine: 'janusgraph',
    displayName: 'JanusGraph',
    family: 'graph',
    maturity: 'beta',
    defaultLanguage: 'gremlin',
    queryLanguages: ['gremlin'],
    connectionModes: ['native', 'connection-string'],
    primaryConnectionMechanisms: [
      'Gremlin Server/WebSocket endpoint',
      'Backend-aware connection profile for storage and index services',
    ],
    defaultPort: 8182,
    managementModel: 'Distributed graph layer over storage/index backends with schema, property keys, labels, composite/mixed indexes, and index lifecycle state.',
    queryModel: 'Gremlin editor and graph renderer, with management API workflows for schema and index lifecycle.',
    presentationModel: 'Graph, table, JSON, schema/index status, backend health, and profile-like metrics where available.',
    securityModel: 'Gremlin endpoint auth, backend-specific auth, network ACLs, TLS, and guarded schema/index operations.',
    resultRenderers: [...graphRenderers, 'metrics'],
    capabilities: [
      'supports_graph_view',
      'supports_schema_browser',
      'supports_result_snapshots',
      'supports_admin_operations',
      'supports_index_management',
      'supports_query_profile',
      'supports_metrics_collection',
      'supports_structure_visualization',
    ],
    baselineFeatures: [
      'Schema, index, property, and label browser',
      'Gremlin editor',
      'Graph renderer',
      'Backend health summary',
    ],
    advancedFeatures: [
      'Index lifecycle and reindex status',
      'Mixed-index operations',
      'Backend health drilldown',
      'Schema management workflows',
    ],
    diagnosticFeatures: [
      'Index status panels',
      'Backend health readouts',
      'Traversal timing where available',
      'Guarded schema mutations',
    ],
    analyticsSignals: [
      'Traversal duration',
      'Index lifecycle state',
      'Backend latency',
      'Vertex and edge sample counts',
    ],
  },
  {
    engine: 'influxdb',
    displayName: 'InfluxDB',
    family: 'timeseries',
    maturity: 'beta',
    defaultLanguage: 'influxql',
    queryLanguages: ['flux', 'influxql', 'sql'],
    connectionModes: ['native', 'connection-string'],
    primaryConnectionMechanisms: [
      'InfluxDB HTTP API with token',
      'Version-specific URL and org/bucket profile',
    ],
    defaultPort: 8086,
    managementModel: 'Time-series buckets/databases with measurements, fields, tags, retention, tasks, tokens, and version-specific query engines.',
    queryModel: 'Query editor for Flux, InfluxQL, or SQL by version plus visual measurement/tag/field builder.',
    presentationModel: 'Chart-ready series, tables, bucket metadata, cardinality, task/retention status, and metrics.',
    securityModel: 'Token scopes, org/bucket permissions, TLS, read-only profiles, and guarded write/import tasks.',
    resultRenderers: [...seriesRenderers],
    capabilities: [
      'supports_time_series_charting',
      'supports_schema_browser',
      'supports_visual_query_builder',
      'supports_result_snapshots',
      'supports_admin_operations',
      'supports_permission_inspection',
      'supports_query_profile',
      'supports_metrics_collection',
      'supports_import_export',
      'supports_streaming_results',
    ],
    baselineFeatures: [
      'Bucket, measurement, field, and tag explorer',
      'Version-aware query editor',
      'Line protocol import',
      'Series and table renderers',
    ],
    advancedFeatures: [
      'Retention and task management',
      'Cardinality analysis',
      'Dashboard-ready series',
      'v1/v2/v3 compatibility',
    ],
    diagnosticFeatures: [
      'Cardinality warnings',
      'Query profile where available',
      'Task/retention status',
      'Token permission explanations',
    ],
    analyticsSignals: [
      'Series cardinality',
      'Query duration',
      'Bucket storage',
      'Task success/failure counts',
    ],
  },
  {
    engine: 'prometheus',
    displayName: 'Prometheus',
    family: 'timeseries',
    maturity: 'beta',
    defaultLanguage: 'promql',
    queryLanguages: ['promql'],
    connectionModes: ['native', 'connection-string'],
    primaryConnectionMechanisms: [
      'Prometheus HTTP API',
      'URL profile behind auth proxy or service mesh',
    ],
    defaultPort: 9090,
    managementModel: 'Metrics TSDB with series, labels, targets, rules, alerts, TSDB/head status, and optional auth handled outside core Prometheus.',
    queryModel: 'PromQL editor plus metric/label/range query builder for instant and range queries.',
    presentationModel: 'Range charts, instant vectors, tables, label/series metadata, alert/rule panels, and TSDB metrics.',
    securityModel: 'External auth proxy, network policy, TLS, read-only profiles, and warnings for expensive label/series queries.',
    resultRenderers: ['series', 'chart', 'table', 'metrics', 'json'],
    capabilities: [
      'supports_time_series_charting',
      'supports_schema_browser',
      'supports_visual_query_builder',
      'supports_result_snapshots',
      'supports_query_profile',
      'supports_metrics_collection',
      'supports_streaming_results',
    ],
    baselineFeatures: [
      'PromQL editor',
      'Series, label, target, and rule browser',
      'Instant/range query rendering',
      'Chart and table output',
    ],
    advancedFeatures: [
      'Alerts, rules, and status panels',
      'TSDB/head stats',
      'Recording-rule insights',
      'Expensive query warnings',
    ],
    diagnosticFeatures: [
      'Target health dashboard',
      'Rule evaluation status',
      'TSDB/head stats',
      'Label cardinality warnings',
    ],
    analyticsSignals: [
      'Sample counts',
      'Query duration',
      'Target up/down state',
      'Rule evaluation duration',
    ],
  },
  {
    engine: 'opentsdb',
    displayName: 'OpenTSDB',
    family: 'timeseries',
    maturity: 'beta',
    defaultLanguage: 'opentsdb',
    queryLanguages: ['opentsdb', 'json'],
    connectionModes: ['native', 'connection-string'],
    primaryConnectionMechanisms: [
      'OpenTSDB HTTP API',
      'Telnet protocol for legacy workflows',
    ],
    defaultPort: 4242,
    managementModel: 'HBase-backed time-series store with metrics, tags, aggregators, downsampling, UID metadata, trees, and stats endpoints.',
    queryModel: 'Metric/tag query builder with aggregator and downsample controls plus raw API JSON.',
    presentationModel: 'Chart-ready series, tables, raw API output, stats panels, UID/tree metadata, and warnings.',
    securityModel: 'No native auth in many deployments, so Universality should surface network ACL/auth-proxy warnings and read-only guardrails.',
    resultRenderers: [...seriesRenderers, 'raw'],
    capabilities: [
      'supports_time_series_charting',
      'supports_schema_browser',
      'supports_visual_query_builder',
      'supports_result_snapshots',
      'supports_admin_operations',
      'supports_metrics_collection',
      'supports_import_export',
    ],
    baselineFeatures: [
      'Metric and tag explorer',
      'Query builder with aggregator and downsample controls',
      'Series chart rendering',
      'Raw API response view',
    ],
    advancedFeatures: [
      '/api/stats dashboards',
      'UID and tree management',
      'Network ACL warnings',
      'HBase backend status hooks',
    ],
    diagnosticFeatures: [
      'API stats panels',
      'Missing-auth warnings',
      'High-cardinality tag warnings',
      'UID/tree health checks',
    ],
    analyticsSignals: [
      'Returned datapoints',
      'Query duration',
      'API stats counters',
      'Metric/tag cardinality samples',
    ],
  },
  {
    engine: 'elasticsearch',
    displayName: 'Elasticsearch',
    family: 'search',
    maturity: 'beta',
    defaultLanguage: 'query-dsl',
    queryLanguages: ['query-dsl', 'esql', 'sql', 'json'],
    connectionModes: ['native', 'connection-string', 'cloud-iam'],
    primaryConnectionMechanisms: [
      'Elasticsearch HTTP API',
      'Elastic Cloud endpoint/API key',
    ],
    defaultPort: 9200,
    managementModel: 'Search/analytics/vector cluster with indices, data streams, mappings, templates, aliases, ILM, snapshots, shards, roles, and privileges.',
    queryModel: 'Query DSL editor, ES|QL/SQL editors, and visual search/filter/aggregation builder.',
    presentationModel: 'Search hits, aggregations, charts, mappings, explain/profile output, shard/segment stats, and vector-search results.',
    securityModel: 'RBAC users/roles, API keys, index privileges, TLS, cloud auth, read-only profiles, and guarded destructive index actions.',
    resultRenderers: ['searchHits', 'json', 'table', 'chart', 'plan', 'profile', 'metrics'],
    capabilities: [
      'supports_schema_browser',
      'supports_visual_query_builder',
      'supports_result_snapshots',
      'supports_admin_operations',
      'supports_index_management',
      'supports_user_role_browser',
      'supports_permission_inspection',
      'supports_explain_plan',
      'supports_plan_visualization',
      'supports_query_profile',
      'supports_metrics_collection',
      'supports_cloud_iam',
      'supports_import_export',
      'supports_backup_restore',
      'supports_vector_search',
      'supports_structure_visualization',
    ],
    baselineFeatures: [
      'Cluster, index, data stream, and mapping browser',
      'Query DSL editor',
      'Search hits and aggregation charts',
      'Index template and alias viewer',
    ],
    advancedFeatures: [
      'Explain/profile renderer',
      'Shard, segment, and cat stats',
      'Role/index privilege viewer',
      'ILM and snapshot workflows later',
    ],
    diagnosticFeatures: [
      'Profile tree',
      'Explain output',
      'Shard/segment dashboards',
      'Privilege-aware index actions',
    ],
    analyticsSignals: [
      'Hits, took, and timed_out',
      'Aggregation buckets',
      'Shard failures',
      'Index size and segment counts',
    ],
  },
  {
    engine: 'opensearch',
    displayName: 'OpenSearch',
    family: 'search',
    maturity: 'beta',
    defaultLanguage: 'query-dsl',
    queryLanguages: ['query-dsl', 'sql', 'json'],
    connectionModes: ['native', 'connection-string', 'cloud-iam'],
    primaryConnectionMechanisms: [
      'OpenSearch HTTP API',
      'Managed OpenSearch endpoint with SigV4 or basic auth',
    ],
    defaultPort: 9200,
    managementModel: 'Elasticsearch-derived search/analytics cluster with indices, mappings, data streams, Dashboards plugins, security plugin, ISM, shards, and snapshots.',
    queryModel: 'Query DSL editor, SQL plugin editor where available, and visual search/filter/aggregation builder.',
    presentationModel: 'Search hits, aggregations, charts, mappings, profile output, plugin metrics, and shard stats.',
    securityModel: 'Security plugin users/roles/tenants, index privileges, SigV4/IAM on managed services, TLS, and guarded index actions.',
    resultRenderers: ['searchHits', 'json', 'table', 'chart', 'plan', 'profile', 'metrics'],
    capabilities: [
      'supports_schema_browser',
      'supports_visual_query_builder',
      'supports_result_snapshots',
      'supports_admin_operations',
      'supports_index_management',
      'supports_user_role_browser',
      'supports_permission_inspection',
      'supports_explain_plan',
      'supports_plan_visualization',
      'supports_query_profile',
      'supports_metrics_collection',
      'supports_cloud_iam',
      'supports_import_export',
      'supports_backup_restore',
      'supports_vector_search',
      'supports_structure_visualization',
    ],
    baselineFeatures: [
      'Cluster, index, data stream, and mapping browser',
      'Query DSL editor',
      'Search hits and aggregation charts',
      'Separate adapter/version detection',
    ],
    advancedFeatures: [
      'Plugin-aware security browser',
      'Performance Analyzer panels',
      'Index State Management workflows',
      'Snapshot workflows later',
    ],
    diagnosticFeatures: [
      'Profile tree',
      'Shard and segment dashboards',
      'Performance Analyzer metrics',
      'Security plugin permission explanations',
    ],
    analyticsSignals: [
      'Hits, took, and shard failures',
      'Aggregation buckets',
      'Index size and segment counts',
      'Plugin metrics',
    ],
  },
  {
    engine: 'clickhouse',
    displayName: 'ClickHouse',
    family: 'warehouse',
    maturity: 'beta',
    defaultLanguage: 'clickhouse-sql',
    queryLanguages: ['clickhouse-sql', 'sql'],
    connectionModes: ['native', 'connection-string'],
    primaryConnectionMechanisms: [
      'ClickHouse HTTP or native protocol',
      'Connection string with database/user/secret references',
    ],
    defaultPort: 8123,
    managementModel: 'Columnar OLAP databases with tables, materialized views, dictionaries, system tables, RBAC, clusters, query logs, and metrics.',
    queryModel: 'ClickHouse SQL editor plus visual table/filter/aggregation builder and import/export workflows.',
    presentationModel: 'Tables, charts, schema metadata, EXPLAIN pipeline, query profile, system.query_log panels, and metrics dashboards.',
    securityModel: 'Users, roles, row policies, quotas, TLS, read-only profiles, and guarded mutations/DDL.',
    resultRenderers: ['table', 'chart', 'schema', 'plan', 'profile', 'metrics'],
    capabilities: [
      ...SQL_CORE,
      ...SQL_ADMIN,
      'supports_visual_query_builder',
      'supports_query_cancellation',
      'supports_streaming_results',
      'supports_import_export',
      'supports_structure_visualization',
    ],
    baselineFeatures: [
      'Database, table, and materialized-view browser',
      'ClickHouse SQL editor',
      'Import/export workflows',
      'Chart-ready analytical results',
    ],
    advancedFeatures: [
      'EXPLAIN pipeline renderer',
      'system.query_log dashboards',
      'Metrics dashboards',
      'Cluster topology',
    ],
    diagnosticFeatures: [
      'Pipeline visualization',
      'Query log drilldown',
      'Memory and read-byte warnings',
      'Cluster health panels',
    ],
    analyticsSignals: [
      'Read rows/bytes and result rows',
      'Memory usage',
      'Query duration',
      'Selected parts and partitions',
    ],
  },
  {
    engine: 'duckdb',
    displayName: 'DuckDB',
    family: 'embedded-olap',
    maturity: 'beta',
    defaultLanguage: 'sql',
    queryLanguages: ['sql'],
    connectionModes: ['local-file', 'connection-string'],
    primaryConnectionMechanisms: [
      'Local DuckDB database file',
      'In-process connection string with local file and extension settings',
    ],
    managementModel: 'Embedded OLAP engine with schemas, tables, views, PRAGMA metadata, extensions, and direct CSV/Parquet/Arrow analytics.',
    queryModel: 'SQL editor for local-file analytics plus visual CSV/Parquet import and table/view builders.',
    presentationModel: 'Tables, charts, PRAGMA metadata, EXPLAIN/ANALYZE/profiling output, and export files.',
    securityModel: 'Local file permissions, extension trust, read-only profiles, and guardrails for file-writing/export operations.',
    resultRenderers: ['table', 'chart', 'schema', 'plan', 'profile', 'metrics'],
    capabilities: [
      ...SQL_CORE,
      'supports_local_database_creation',
      'supports_admin_operations',
      'supports_index_management',
      'supports_explain_plan',
      'supports_plan_visualization',
      'supports_query_profile',
      'supports_metrics_collection',
      'supports_visual_query_builder',
      'supports_import_export',
      'supports_backup_restore',
      'supports_structure_visualization',
    ],
    baselineFeatures: [
      'Open/create local DuckDB database',
      'Table, view, and schema browser',
      'SQL over CSV and Parquet',
      'Import/export workflows',
    ],
    advancedFeatures: [
      'EXPLAIN/ANALYZE/profiling',
      'PRAGMA metadata panels',
      'Extension manager',
      'Local-file analytics templates',
    ],
    diagnosticFeatures: [
      'Profiling renderer',
      'Extension and file access warnings',
      'PRAGMA metadata output',
      'Large local result warnings',
    ],
    analyticsSignals: [
      'Rows scanned and returned',
      'Operator duration',
      'File size and format',
      'Memory and temp storage usage',
    ],
  },
  {
    engine: 'snowflake',
    displayName: 'Snowflake',
    family: 'warehouse',
    maturity: 'beta',
    defaultLanguage: 'snowflake-sql',
    queryLanguages: ['snowflake-sql', 'sql'],
    connectionModes: ['native', 'connection-string', 'cloud-sdk'],
    primaryConnectionMechanisms: [
      'Snowflake driver connection',
      'Account URL with role, warehouse, authenticator, and secret references',
    ],
    defaultPort: 443,
    managementModel: 'Cloud warehouse with accounts, databases, schemas, tables, views, stages, warehouses, roles, grants, tasks, streams, shares, and query history.',
    queryModel: 'Snowflake SQL editor with active role/warehouse selector and visual table/query builder.',
    presentationModel: 'Tables, schema metadata, query profile/history, warehouse utilization, cost estimates, and charts.',
    securityModel: 'Role hierarchy, grants, warehouses, SSO/OAuth/key pair auth, network policies, masking policies, and permission-aware controls.',
    resultRenderers: ['table', 'schema', 'plan', 'profile', 'metrics', 'costEstimate', 'chart'],
    capabilities: [
      ...SQL_CORE,
      ...SQL_ADMIN,
      'supports_visual_query_builder',
      'supports_query_cancellation',
      'supports_cloud_iam',
      'supports_cost_estimation',
      'supports_import_export',
      'supports_structure_visualization',
    ],
    baselineFeatures: [
      'Account, database, schema, table, stage, and warehouse browser',
      'Snowflake SQL editor',
      'Active role and warehouse selector',
      'Saved queries, snapshots, and export',
    ],
    advancedFeatures: [
      'Query history and profile',
      'Cost and warehouse utilization charts',
      'Tasks, streams, and shares',
      'Role/grant inspection',
    ],
    diagnosticFeatures: [
      'Query profile graph',
      'Warehouse utilization dashboard',
      'Credit/cost estimates',
      'Permission-aware disabled actions',
    ],
    analyticsSignals: [
      'Bytes scanned and rows produced',
      'Credits consumed',
      'Warehouse load',
      'Queue and execution time',
    ],
  },
  {
    engine: 'bigquery',
    displayName: 'BigQuery',
    family: 'warehouse',
    maturity: 'beta',
    defaultLanguage: 'google-sql',
    queryLanguages: ['google-sql', 'sql'],
    connectionModes: ['cloud-iam', 'cloud-sdk'],
    primaryConnectionMechanisms: [
      'Google Cloud SDK/Application Default Credentials',
      'Service account or OAuth identity with project/dataset IAM',
    ],
    managementModel: 'Serverless warehouse with projects, datasets, tables, views, jobs, reservations, scheduled queries, IAM, and INFORMATION_SCHEMA.',
    queryModel: 'GoogleSQL editor with dry-run byte estimate, visual dataset/table builder, and job workflow controls.',
    presentationModel: 'Tables, schema metadata, job history, dry-run cost estimates, INFORMATION_SCHEMA metrics, slot usage charts, and dashboards.',
    securityModel: 'Google IAM, dataset/table policy tags, OAuth/ADC/service accounts, read-only profiles, and guarded write/export jobs.',
    resultRenderers: ['table', 'schema', 'profile', 'metrics', 'costEstimate', 'chart', 'json'],
    capabilities: [
      ...SQL_CORE,
      ...SQL_ADMIN,
      ...CLOUD_SECURITY,
      'supports_visual_query_builder',
      'supports_query_cancellation',
      'supports_cost_estimation',
      'supports_import_export',
      'supports_streaming_results',
      'supports_structure_visualization',
    ],
    baselineFeatures: [
      'Project, dataset, table, and job browser',
      'GoogleSQL editor',
      'Dry-run byte estimate',
      'Saved queries, snapshots, and export',
    ],
    advancedFeatures: [
      'INFORMATION_SCHEMA.JOBS performance/cost dashboards',
      'Slot usage panels',
      'Scheduled queries',
      'IAM explanation and permission-aware controls',
    ],
    diagnosticFeatures: [
      'Dry-run cost estimate',
      'Job timeline/profile',
      'Slot utilization dashboard',
      'Large scan warnings',
    ],
    analyticsSignals: [
      'Bytes processed and billed',
      'Slot milliseconds',
      'Job duration',
      'Estimated query cost',
    ],
  },
]

export const BETA_ADAPTER_ENGINES = DATASTORE_FEATURE_BACKLOG.filter(
  (entry) => entry.maturity === 'beta',
).map((entry) => entry.engine)

export const PLANNED_ADAPTER_ENGINES = DATASTORE_FEATURE_BACKLOG.filter(
  (entry) => entry.maturity === 'planned',
).map((entry) => entry.engine)

export const UNIVERSALITY_ADAPTER_MANIFESTS: AdapterManifest[] =
  DATASTORE_FEATURE_BACKLOG.map((entry) => ({
    id: `adapter-${entry.engine}`,
    engine: entry.engine,
    family: entry.family,
    label: `${entry.displayName} adapter`,
    maturity: entry.maturity,
    capabilities: entry.capabilities,
    defaultLanguage: entry.defaultLanguage,
    localDatabase: entry.localDatabase,
  }))

export function datastoreBacklogByEngine(engine: DatastoreEngine) {
  return DATASTORE_FEATURE_BACKLOG.find((entry) => entry.engine === engine)
}
